### ISSUE TITLE
No Game and Any Game game_ids are different for ACUS and ACNW and make queries fragile

### ISSUE THREAD

**Issue by evoskamp** [ggascoigne/amber#109]
Move to author_id being NULL instead

**Comment by ggascoigne** [comment]
the author_id being null fixes the queries, but I'd like to change how those values are identified in general.

I really think that the whole magic number thing was a mistake and I should have uses a flags/type field to id the records.

**Comment by evoskamp** [comment]
Yeah, there's just no way to argue against that.  :-)

Magic numbers, overloading identifiers, and having identifiers have structured meaning always comes back to bite you in the ass.

> the author_id being null fixes the queries, but I'd like to change how those values are identified in general.
> 
> I really think that the whole magic number thing was a mistake and I should have uses a flags/type field to id the records.
