### ISSUE TITLE
Current year should be in Settings?

### ISSUE THREAD

**Issue by evoskamp** [ggascoigne/amber#114]

**Comment by ggascoigne** [comment]
This might not be a bad idea.

Originally, there was no serverless architecture for the UI, we had serverless api calls, but the front end was static, and having year be a runtime rather than a compile time lookup wasn't really practical.  But, now we use Next.js for the pages, we should be able to get this at runtime prior to the initial page paint.  It's possible that it'd still be too janky, there are quite a few really top level things that depend on year,  but it's worth a try.

**Comment by evoskamp** [comment]
Realistically it seems as if all of config.ts could be in settings.

**Comment by ggascoigne** [comment]
If the year works, then yes, I think that it could all go there.

**Comment by evoskamp** [comment]
I like the caveat.

Since I'm waiting to find out when the next ACUS is, as it depends on when spring break and Easter are, I'll try this locally.

**Comment by evoskamp** [comment]
Realistically, I'll want to populate the config context.

Looking at Settings though, that's really all client stuff (or at least currently implemented as such, like routing/permission, features for what type or Yes/No.

Should config really be blended in there?

And, looking at what is in config.ts there's a real mix in there, e.g. the timeline stuff which is really only ever used for display on the home page. Everything else uses the display.* allow.* disable.* values. There's pricing in there. Some config string stuff.

We can use setting, but should we have a "section" filter? Sort of a namespace of what's what, if only for the settings-admin page?

The startDates needs to be populated as it is used off of the year filter. Bit unfriendly out of settings unless you overload the code field to do grouping or lists (e.g. any key with numeric suffix is a dictionary with that numeric suffix as entry, and anything beyond it collapses). Not pretty. Alternatively, have a convention table. I don't know if virtual matters for past ones, as it affects signup and things on ACNW especially. But it's nice to know for past cons. Funnily enough slots matters to ACUS when I add pre-2017 data because when I took over ACUS we had 9 slots.

Still thinking

**Comment by ggascoigne** [comment]
I think that https://github.com/ggascoigne/amber/pull/125 addresses this.  The settings.config is still large, and a bit intertwined, but I added a "add new year action", that should deal with most of it in one go, avoids all of the validation issues that come from needing to create multiple separate fields independently - too easy to hose the system as the config is invalid and not let you make it pass validation again.  The single action bypasses that problem.

I'll leave this one open until you get a chance to test it locally, it's probably not perfect, but I think that it's enough better for now.

**Comment by evoskamp** [comment]
#125 addresses it.
