### ISSUE TITLE
Can't create new setting through UI as it creates duplicate key

### ISSUE THREAD

**Issue by evoskamp** [ggascoigne/amber#119]
Repro: Settings -> + Values test.test/integer/Admin

Error: duplicate key value violates unique constraint "setting_pkey"

**Comment by ggascoigne** [comment]
Heh, yeah I ran into this as well.

https://github.com/ggascoigne/amber/blob/main/packages/database/support/db/migrations/20230429125442_migrate_config_to_settings.js#L212

should fix it.  Came across it doing https://github.com/ggascoigne/amber/pull/125
