### ISSUE TITLE
Ambercon site shows incorrect dates

### ISSUE THREAD

**Issue by ggascoigne** [ggascoigne/amber#145]
Several east coast folk have reported that the dates for acus are off by a day while they look correct to me.  I assume that this is a time zone issue.

**Comment by evoskamp** [comment]
Mmmm, wonder if it shows off by a day around the 3 hour time difference?

**Comment by ggascoigne** [comment]
fixed by https://github.com/ggascoigne/amber/pull/146

**Comment by evoskamp** [comment]
Does it address #133 as well?

**Comment by ggascoigne** [comment]
I'm sure it does. Should have looked for an issue before creating a new one.

**Comment by evoskamp** [comment]
Eh, if I get the reg and game submission up, enough people across timezones will look at it and see if we can close that one as well.  :-)

**Comment by evoskamp** [comment]
I was just looking to update dates on ambercon.com, in the vague hope to get it sorted before I fly out to Vancouver tomorrow at 3pm and noted that for the 2024 dates, in Settings, under Configuration there is conventionStartDate and under Start Dates there is  2024.date.

The former is 3/14/2024, the latter 3/15/2024. It seems the latter can't ever by right (it's the Friday), and I haven't traced where it comes from.

**Comment by evoskamp** [comment]
... but it works, so I'm not going to worry about it.

**Comment by evoskamp** [comment]
The config.startDates entries are also duplicated for good measure. I'd better clean that up.
