### ISSUE TITLE
ACUS: Better explain the new auth system and needing to create a userid

### ISSUE THREAD

**Issue by evoskamp** [ggascoigne/amber#41]
Three people so far keep trying to reset their old userid ...

**Comment by ggascoigne** [comment]
We had the same problem with acnw. It's hard to make people read, too little and they ignore it, too much and they ignore it. 

Btw there is a faq entry on auth issues, maybe we link to it by the login button. 

https://www.ambercon.com/faq

**Comment by evoskamp** [comment]
Yeah. Added some bold text to summarize, a link to the FAQ, and a step-by-step on what to do.
