### ISSUE TITLE
Track $ balance in membership

### ISSUE THREAD

**Issue by evoskamp** [ggascoigne/amber#53]
Necessary as we have some left over memberships from before the pandemic, during the pandemic, etcetera.

Also useful if we have to take payment at the con.

**Comment by evoskamp** [comment]
table membership already contains columns amount_owed and amount_paid. It'll suffice for now.

Moving to a transaction with notes membership_payments table would be nice, and just aggregate instead of the amount_owed and amount_paid, for when people can't attend and want to apply it to next year's, or other.

**Comment by ggascoigne** [comment]
There are columns, but they are currently used for nothing and so can be safely repurposed or removed as needed.  Schema changes are easy as long as we remember that there's one schema for both systems.

**Comment by evoskamp** [comment]
I think this will go with taking on-line payment through Stripe invoices.
