### ISSUE TITLE
ACUS: Maybe add slots_attending in the signing up / editing membership?

### ISSUE THREAD

**Issue by evoskamp** [ggascoigne/amber#58]
Table membership contains slots_attending, but it does not seem to be used.

Especially as people attending less than 4 days know when they are not (or we can ask for the inverse, which may be easier), and even people attending 4 days often don't play certain slots or Sunday nights, we could gather this.

**Comment by ggascoigne** [comment]
it was used for the virtual con, it wouldn't be tricky to add it back to the non-virtual membership and let folks fill it in.

**Comment by evoskamp** [comment]
I'll wait for Kit to tell me. I've found it of extremely limited and low quality data.

We build the game book to numbers that I swag off of GMs, Signups, comparison to previous years' signup curves ...

Not going to touch this yet.

**Comment by evoskamp** [comment]
Not going to do this
