### ISSUE TITLE
ACUS: game choices report for player scheduler drops Any Game choices

### ISSUE THREAD

**Issue by evoskamp** [ggascoigne/amber#89]
The join in the query joins slot from the game, but as Any Game in the game table does not have a slot (it's a generic that can automagically shows up in any slot as a choice), it needs to be joined from the game submission, otherwise the resulting output for slot is null, and it's used in a join.

**Comment by ggascoigne** [comment]
Any game is a valid game choice, but it isn't a valid game assignment. That's intentional.

**Comment by evoskamp** [comment]
That makes perfect sense, but the report I created to pull the game choices joined game its slot to slot and Any Game has no slot, so it dropped them from the result set and I didn't see "Any Game" so it's a bug and I need to change the join to join of for game_submission its slot
